// components/split-calculator/currency-switcher.tsx
'use client'

import { Button } from '@/components/ui/button'
import { CURRENCY_LABELS } from '@/lib/constants'
import type { Currency } from '@/types/split-calculator'

interface CurrencySwitcherProps {
  currency: Currency
  onCurrencyChange: (currency: Currency) => void
}

const currencies: Currency[] = ['jpy', 'usd']

export function CurrencySwitcher({ currency, onCurrencyChange }: CurrencySwitcherProps) {
  return (
    <div className="inline-flex rounded-lg border-2 border-border bg-secondary/50 p-1">
      {currencies.map((c) => (
        <Button
          key={c}
          variant={currency === c ? 'default' : 'ghost'}
          size="sm"
          className={`h-8 px-4 text-sm font-medium ${
            currency === c
              ? 'bg-primary text-primary-foreground'
              : 'text-muted-foreground hover:text-foreground'
          }`}
          onClick={() => onCurrencyChange(c)}
        >
          {CURRENCY_LABELS[c]}
        </Button>
      ))}
    </div>
  )
}

// packages/app/src/lib/components/CurrencySwitcher.svelte
<script lang="ts">
  import type { Currency } from '$lib/types/split-calculator'

  interface Props {
    currency: Currency
    onCurrencyChange: (c: Currency) => void
  }

  let { currency, onCurrencyChange }: Props = $props()
</script>

<div class="inline-flex rounded-lg border-2 border-gray-200 bg-gray-50 p-1">
  <button
    onclick={() => onCurrencyChange('jpy')}
    class="rounded px-4 py-1.5 text-sm font-medium transition-colors {currency === 'jpy'
      ? 'bg-white text-gray-900 shadow-sm'
      : 'text-gray-500 hover:text-gray-700'}"
  >
    JPY ¥
  </button>
  <button
    onclick={() => onCurrencyChange('usd')}
    class="rounded px-4 py-1.5 text-sm font-medium transition-colors {currency === 'usd'
      ? 'bg-white text-gray-900 shadow-sm'
      : 'text-gray-500 hover:text-gray-700'}"
  >
    USD $
  </button>
</div>
