// components/split-calculator/currency-switcher.tsx
'use client'

import { Button } from '@/components/ui/button'
import { CURRENCY_LABELS } from '@/lib/constants'
import type { Currency } from '@/types/split-calculator'

interface CurrencySwitcherProps {
  currency: Currency
  onCurrencyChange: (currency: Currency) => void
}

const currencies: Currency[] = ['jpy', 'usd']

export function CurrencySwitcher({ currency, onCurrencyChange }: CurrencySwitcherProps) {
  return (
    <div className="inline-flex rounded-lg border-2 border-border bg-secondary/50 p-1">
      {currencies.map((c) => (
        <Button
          key={c}
          variant={currency === c ? 'default' : 'ghost'}
          size="sm"
          className={`h-8 px-4 text-sm font-medium ${
            currency === c
              ? 'bg-primary text-primary-foreground'
              : 'text-muted-foreground hover:text-foreground'
          }`}
          onClick={() => onCurrencyChange(c)}
        >
          {CURRENCY_LABELS[c]}
        </Button>
      ))}
    </div>
  )
}

// src/lib/components/currency-switcher.svelte
<script lang="ts">
  import type { Currency } from '$lib/types/split-calculator'

  let {
    currency,
    oncurrencychange
  }: {
    currency: Currency
    oncurrencychange: (c: Currency) => void
  } = $props()
</script>

<div class="inline-flex rounded-lg overflow-hidden border border-gray-300 dark:border-gray-600">
  <button
    type="button"
    class="px-3 py-1.5 text-sm font-medium transition-colors {currency === 'jpy'
      ? 'bg-indigo-600 text-white'
      : 'bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700'}"
    onclick={() => currency !== 'jpy' && oncurrencychange('jpy')}
  >
    JPY
  </button>
  <button
    type="button"
    class="px-3 py-1.5 text-sm font-medium transition-colors border-l border-gray-300 dark:border-gray-600 {currency === 'usd'
      ? 'bg-indigo-600 text-white'
      : 'bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700'}"
    onclick={() => currency !== 'usd' && oncurrencychange('usd')}
  >
    USD
  </button>
</div>
