// components/split-calculator/expense-list.tsx
'use client'

import { Trash2 } from 'lucide-react'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import type { Currency, Expense, Member } from '@/types/split-calculator'
import { MemberAvatar } from './member-avatar'

interface ExpenseListProps {
  expenses: Expense[]
  members: Member[]
  currentCurrency: Currency
  onRemoveExpense: (id: string) => void
  formatCurrency: (amount: number) => string
}

export function ExpenseList({
  expenses,
  members,
  currentCurrency,
  onRemoveExpense,
  formatCurrency,
}: ExpenseListProps) {
  const getMember = (id: string) => members.find((m) => m.id === id)
  const getMemberName = (id: string) => getMember(id)?.name || ''

  if (expenses.length === 0) return null

  return (
    <Card className="mb-6 border-2 border-border">
      <CardHeader className="pb-3">
        <CardTitle className="text-lg">支出一覧</CardTitle>
      </CardHeader>
      <CardContent>
        <ul className="space-y-3">
          {expenses.map((expense) => {
            const payer = getMember(expense.paidById)
            return (
              <li
                key={expense.id}
                className="flex items-center justify-between rounded-lg border-2 border-border bg-secondary/30 p-3"
              >
                <div className="flex min-w-0 flex-1 items-center gap-3">
                  {payer && <MemberAvatar member={payer} />}
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <p className="truncate font-medium text-foreground">{expense.description}</p>
                      {expense.currency && expense.currency !== currentCurrency && (
                        <Badge variant="outline" className="shrink-0 text-xs">
                          {expense.currency.toUpperCase()}
                        </Badge>
                      )}
                    </div>
                    <p className="truncate text-sm text-muted-foreground">
                      {getMemberName(expense.paidById)} が {formatCurrency(expense.amount)} 支払い
                    </p>
                  </div>
                </div>
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="shrink-0 text-destructive hover:bg-destructive/10 hover:text-destructive"
                      aria-label={`${expense.description}を削除`}
                    >
                      <Trash2 className="h-4 w-4" aria-hidden="true" />
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>支出を削除しますか？</AlertDialogTitle>
                      <AlertDialogDescription>
                        「{expense.description}」（{formatCurrency(expense.amount)}
                        ）を削除します。この操作は取り消せません。
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>キャンセル</AlertDialogCancel>
                      <AlertDialogAction
                        onClick={() => onRemoveExpense(expense.id)}
                        className="bg-destructive text-white hover:bg-destructive/90"
                      >
                        削除する
                      </AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              </li>
            )
          })}
        </ul>
      </CardContent>
    </Card>
  )
}

// src/lib/components/ExpenseList.svelte
<script lang="ts">
  import { Receipt, Trash2 } from 'lucide-svelte'
  import type { Currency, Expense, Member } from '$lib/types/split-calculator'
  import MemberAvatar from './MemberAvatar.svelte'

  interface Props {
    expenses: Expense[]
    members: Member[]
    currentCurrency: Currency
    formatCurrency: (amount: number) => string
    onRemoveExpense: (id: string) => void
  }

  let { expenses, members, currentCurrency, formatCurrency, onRemoveExpense }: Props = $props()

  function getMember(id: string): Member | undefined {
    return members.find((m) => m.id === id)
  }
</script>

{#if expenses.length > 0}
  <div class="mb-6 rounded-xl border-2 border-gray-200 bg-white">
    <div class="border-b border-gray-100 px-4 py-3">
      <h2 class="flex items-center gap-2 font-semibold text-gray-800">
        <Receipt class="h-4 w-4 text-blue-600" />
        支出一覧 ({expenses.length}件)
      </h2>
    </div>
    <ul class="divide-y divide-gray-50">
      {#each [...expenses].reverse() as expense (expense.id)}
        {@const payer = getMember(expense.paidById)}
        <li class="flex items-center gap-3 px-4 py-3">
          {#if payer}
            <MemberAvatar member={payer} size="sm" />
          {/if}
          <div class="min-w-0 flex-1">
            <p class="truncate text-sm font-medium text-gray-800">{expense.description}</p>
            <p class="text-xs text-gray-400">{payer?.name ?? '不明'}</p>
          </div>
          <div class="flex shrink-0 items-center gap-2">
            {#if expense.currency !== currentCurrency}
              <span
                class="rounded-full bg-amber-100 px-2 py-0.5 text-xs font-medium text-amber-700"
              >
                {expense.currency.toUpperCase()}
              </span>
            {/if}
            <span class="text-sm font-semibold text-gray-900">{formatCurrency(expense.amount)}</span>
            <button
              onclick={() => onRemoveExpense(expense.id)}
              class="rounded p-1 text-gray-300 hover:text-red-500"
              aria-label="{expense.description}を削除"
            >
              <Trash2 class="h-4 w-4" />
            </button>
          </div>
        </li>
      {/each}
    </ul>
  </div>
{/if}
