// components/split-calculator/expense-list.tsx
'use client'

import { Trash2 } from 'lucide-react'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import type { Currency, Expense, Member } from '@/types/split-calculator'
import { MemberAvatar } from './member-avatar'

interface ExpenseListProps {
  expenses: Expense[]
  members: Member[]
  currentCurrency: Currency
  onRemoveExpense: (id: string) => void
  formatCurrency: (amount: number) => string
}

export function ExpenseList({
  expenses,
  members,
  currentCurrency,
  onRemoveExpense,
  formatCurrency,
}: ExpenseListProps) {
  const getMember = (id: string) => members.find((m) => m.id === id)
  const getMemberName = (id: string) => getMember(id)?.name || ''

  if (expenses.length === 0) return null

  return (
    <Card className="mb-6 border-2 border-border">
      <CardHeader className="pb-3">
        <CardTitle className="text-lg">支出一覧</CardTitle>
      </CardHeader>
      <CardContent>
        <ul className="space-y-3">
          {expenses.map((expense) => {
            const payer = getMember(expense.paidById)
            return (
              <li
                key={expense.id}
                className="flex items-center justify-between rounded-lg border-2 border-border bg-secondary/30 p-3"
              >
                <div className="flex min-w-0 flex-1 items-center gap-3">
                  {payer && <MemberAvatar member={payer} />}
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <p className="truncate font-medium text-foreground">{expense.description}</p>
                      {expense.currency && expense.currency !== currentCurrency && (
                        <Badge variant="outline" className="shrink-0 text-xs">
                          {expense.currency.toUpperCase()}
                        </Badge>
                      )}
                    </div>
                    <p className="truncate text-sm text-muted-foreground">
                      {getMemberName(expense.paidById)} が {formatCurrency(expense.amount)} 支払い
                    </p>
                  </div>
                </div>
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="shrink-0 text-destructive hover:bg-destructive/10 hover:text-destructive"
                      aria-label={`${expense.description}を削除`}
                    >
                      <Trash2 className="h-4 w-4" aria-hidden="true" />
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>支出を削除しますか？</AlertDialogTitle>
                      <AlertDialogDescription>
                        「{expense.description}」（{formatCurrency(expense.amount)}
                        ）を削除します。この操作は取り消せません。
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>キャンセル</AlertDialogCancel>
                      <AlertDialogAction
                        onClick={() => onRemoveExpense(expense.id)}
                        className="bg-destructive text-white hover:bg-destructive/90"
                      >
                        削除する
                      </AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              </li>
            )
          })}
        </ul>
      </CardContent>
    </Card>
  )
}

// src/lib/components/expense-list.svelte
<script lang="ts">
  import type { Expense, Member, Currency, BtcPrice } from '$lib/types/split-calculator'

  let { expenses, members, currency, btcPrice, onremove }: {
    expenses: Expense[]
    members: Member[]
    currency: Currency
    btcPrice: BtcPrice | null
    onremove: (id: string) => void
  } = $props()

  function getMemberName(id: string): string {
    return members.find((m) => m.id === id)?.name ?? '不明'
  }

  function formatAmount(amount: number, cur: Currency): string {
    if (cur === 'jpy') {
      return new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY' }).format(amount)
    }
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount)
  }
</script>

<div class="space-y-2">
  {#if expenses.length === 0}
    <p class="text-center text-gray-500 dark:text-gray-400 py-6 text-sm">支出がありません</p>
  {:else}
    {#each expenses as expense (expense.id)}
      <div class="flex items-center justify-between gap-3 rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 px-4 py-3">
        <div class="min-w-0 flex-1">
          <p class="truncate font-medium text-gray-900 dark:text-gray-100 text-sm">
            {expense.description}
          </p>
          <p class="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
            {getMemberName(expense.paidById)} が支払い
          </p>
        </div>
        <div class="flex items-center gap-3 flex-shrink-0">
          <span class="font-semibold text-gray-900 dark:text-gray-100 text-sm tabular-nums">
            {formatAmount(expense.amount, expense.currency)}
          </span>
          <button
            type="button"
            onclick={() => onremove(expense.id)}
            class="inline-flex items-center justify-center w-7 h-7 rounded-md text-gray-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors"
            aria-label="削除"
          >
            <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
            </svg>
          </button>
        </div>
      </div>
    {/each}
  {/if}
</div>
