// components/split-calculator/expense-form.tsx
"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Receipt } from "lucide-react"
import type { Member, Expense, Currency } from "@/types/split-calculator"

interface ExpenseFormProps {
  members: Member[]
  onAddExpense: (expense: Expense) => void
  currency: Currency
  currencySymbol: string
}

export function ExpenseForm({
  members,
  onAddExpense,
  currency,
  currencySymbol,
}: ExpenseFormProps) {
  const [newExpense, setNewExpense] = useState({
    description: "",
    amount: "",
    paidById: "",
  })

  const addExpense = () => {
    if (newExpense.description && newExpense.amount && newExpense.paidById) {
      onAddExpense({
        id: crypto.randomUUID(),
        description: newExpense.description,
        amount: Number(newExpense.amount),
        paidById: newExpense.paidById,
        currency: currency,
      })
      setNewExpense({ description: "", amount: "", paidById: "" })
    }
  }

  return (
    <Card className="mb-6 border-2 border-border">
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-lg">
          <Receipt className="h-5 w-5 text-primary" />
          支出を追加
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div>
            <Label htmlFor="paidBy" className="text-sm font-medium">
              支払った人
            </Label>
            <Select
              value={newExpense.paidById}
              onValueChange={(value) => setNewExpense({ ...newExpense, paidById: value })}
              disabled={members.length === 0}
            >
              <SelectTrigger 
                id="paidBy"
                className="mt-1 border-2"
                aria-describedby={members.length === 0 ? "paidby-hint" : undefined}
              >
                <SelectValue placeholder={members.length === 0 ? "先にメンバーを追加" : "選択してください"} />
              </SelectTrigger>
              {members.length === 0 && (
                <p id="paidby-hint" className="sr-only">
                  メンバーを追加してから選択してください
                </p>
              )}
              <SelectContent>
                {members.map((member) => (
                  <SelectItem key={member.id} value={member.id}>
                    <div className="flex max-w-[200px] items-center gap-2">
                      {member.nostrProfile?.picture && (
                        <Avatar className="h-5 w-5 shrink-0">
                          <AvatarImage src={member.nostrProfile.picture || "/placeholder.svg"} alt={member.name} />
                          <AvatarFallback className="text-xs">{member.name.slice(0, 1)}</AvatarFallback>
                        </Avatar>
                      )}
                      <span className="truncate">{member.name}</span>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div>
            <Label htmlFor="description" className="text-sm font-medium">
              内容
            </Label>
            <Input
              id="description"
              placeholder="例：ランチ代"
              value={newExpense.description}
              onChange={(e) => setNewExpense({ ...newExpense, description: e.target.value })}
              className="mt-1 border-2"
            />
          </div>
          <div>
            <Label htmlFor="amount" className="text-sm font-medium">
              金額 ({currency.toUpperCase()})
            </Label>
            <div className="relative mt-1">
              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
                {currencySymbol}
              </span>
              <Input
                id="amount"
                type="number"
                placeholder="0"
                value={newExpense.amount}
                onChange={(e) => setNewExpense({ ...newExpense, amount: e.target.value })}
                className="border-2 pl-8"
              />
            </div>
          </div>
          <Button
            onClick={addExpense}
            className="w-full bg-primary text-primary-foreground hover:bg-primary/90"
            disabled={!newExpense.description || !newExpense.amount || !newExpense.paidById}
          >
            追加する
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}

// src/lib/components/ExpenseForm.svelte
<script lang="ts">
  import { PlusCircle } from 'lucide-svelte'
  import type { Currency, Expense, Member } from '$lib/types/split-calculator'

  interface Props {
    members: Member[]
    currency: Currency
    currencySymbol: string
    onAddExpense: (expense: Expense) => void | Promise<void>
  }

  let { members, currency, currencySymbol, onAddExpense }: Props = $props()

  let description = $state('')
  let amount = $state('')
  let paidById = $state('')

  // Reset paidById when members change and selection is invalid
  $effect(() => {
    if (paidById && !members.find((m) => m.id === paidById)) {
      paidById = members[0]?.id ?? ''
    }
    if (!paidById && members.length > 0) {
      paidById = members[0].id
    }
  })

  const isValid = $derived(
    description.trim().length > 0 && Number(amount) > 0 && paidById !== ''
  )

  function submit() {
    if (!isValid) return
    onAddExpense({
      id: crypto.randomUUID(),
      description: description.trim(),
      amount: Number(amount),
      paidById,
      currency,
    })
    description = ''
    amount = ''
  }
</script>

<div class="mb-6 rounded-xl border-2 border-gray-200 bg-white">
  <div class="border-b border-gray-100 px-4 py-3">
    <h2 class="font-semibold text-gray-800">支出を追加</h2>
  </div>
  <div class="space-y-3 p-4">
    <div>
      <label for="expense-desc" class="mb-1 block text-xs font-medium text-gray-600">内容</label>
      <input
        id="expense-desc"
        type="text"
        placeholder="例: 夕食代"
        bind:value={description}
        onkeydown={(e) => e.key === 'Enter' && submit()}
        class="w-full rounded-lg border-2 border-gray-200 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
      />
    </div>
    <div class="grid grid-cols-2 gap-3">
      <div>
        <label for="expense-amount" class="mb-1 block text-xs font-medium text-gray-600">
          金額 ({currencySymbol})
        </label>
        <input
          id="expense-amount"
          type="number"
          min="0"
          placeholder="0"
          bind:value={amount}
          onkeydown={(e) => e.key === 'Enter' && submit()}
          class="w-full rounded-lg border-2 border-gray-200 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
        />
      </div>
      <div>
        <label for="expense-payer" class="mb-1 block text-xs font-medium text-gray-600"
          >支払者</label
        >
        <select
          id="expense-payer"
          bind:value={paidById}
          class="w-full rounded-lg border-2 border-gray-200 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
        >
          {#each members as member (member.id)}
            <option value={member.id}>{member.name}</option>
          {/each}
        </select>
      </div>
    </div>
    <button
      onclick={submit}
      disabled={!isValid}
      class="flex w-full items-center justify-center gap-2 rounded-lg bg-blue-600 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-40"
    >
      <PlusCircle class="h-4 w-4" />
      追加
    </button>
  </div>
</div>
