// components/split-calculator/member-avatar.tsx
'use client'

import Image from 'next/image'
import { useState } from 'react'
import type { Member } from '@/types/split-calculator'

interface MemberAvatarProps {
  member: Member
  size?: number
}

export function MemberAvatar({ member, size = 32 }: MemberAvatarProps) {
  const [imageError, setImageError] = useState(false)
  const initials = member.name.slice(0, 2)

  if (member.nostrProfile?.picture && !imageError) {
    return (
      <div
        className="relative shrink-0 overflow-hidden rounded-full border-2 border-border"
        style={{ width: size, height: size }}
      >
        <Image
          src={member.nostrProfile.picture || '/placeholder.svg'}
          alt={`${member.name}のアバター`}
          fill
          sizes={`${size}px`}
          className="object-cover"
          onError={() => setImageError(true)}
          unoptimized
        />
      </div>
    )
  }

  return (
    <div
      className="flex shrink-0 items-center justify-center rounded-full bg-secondary text-xs font-medium text-secondary-foreground"
      style={{ width: size, height: size }}
      role="img"
      aria-label={`${member.name}のアバター`}
    >
      {initials}
    </div>
  )
}

// src/lib/components/MemberAvatar.svelte
<script lang="ts">
  import type { Member } from '$lib/types/split-calculator'

  interface Props {
    member: Member
    size?: 'sm' | 'md'
  }

  let { member, size = 'md' }: Props = $props()

  const sizeClass = $derived(size === 'sm' ? 'h-6 w-6 text-xs' : 'h-9 w-9 text-sm')
  const initials = $derived(member.name.slice(0, 2).toUpperCase())
</script>

{#if member.nostrProfile?.picture}
  <img
    src={member.nostrProfile.picture}
    alt={member.name}
    class="rounded-full object-cover {sizeClass}"
  />
{:else}
  <div
    class="flex shrink-0 items-center justify-center rounded-full bg-blue-100 font-medium text-blue-700 {sizeClass}"
  >
    {initials}
  </div>
{/if}
