// components/split-calculator-sync.tsx
'use client'

import { AlertTriangle, ArrowLeft, Receipt, Users } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { LightningPaymentModal } from '@/components/lightning-payment-modal'
import { CurrencySwitcher } from '@/components/split-calculator/currency-switcher'
import { ExpenseForm } from '@/components/split-calculator/expense-form'
import { ExpenseList } from '@/components/split-calculator/expense-list'
import { LockSettlementDialog } from '@/components/split-calculator/lock-settlement-dialog'
import { MemberList } from '@/components/split-calculator/member-list'
import { PriceFooter } from '@/components/split-calculator/price-footer'
import { SettlementHeader } from '@/components/split-calculator/settlement-header'
import { SettlementList } from '@/components/split-calculator/settlement-list'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { useBtcPrice } from '@/hooks/use-btc-price'
import { useCurrency } from '@/hooks/use-currency'
import {
  type ConnectionStatus,
  generateInviteLink,
  useSettlementSync,
} from '@/lib/nostr/settlement/hooks'
import type { SettlementState } from '@/lib/nostr/settlement/state'

import type { Currency, Expense, Member, Settlement } from '@/types/split-calculator'

interface SplitCalculatorSyncProps {
  settlementId: string
  inviteToken: string
  onBack: () => void
}

// Convert SettlementState to UI types
function stateToMembers(state: SettlementState | null): Member[] {
  if (!state?.members) return []
  return state.members.map((m) => ({
    id: m.pubkey,
    name: m.name,
    npub: m.pubkey,
  }))
}

function stateToExpenses(state: SettlementState | null): Expense[] {
  if (!state?.expenses) return []
  return state.expenses.map((e) => ({
    id: e.eventId,
    description: e.note,
    amount: e.amount,
    paidById: e.memberPubkey,
    currency: (e.currency?.toLowerCase() || 'jpy') as Currency,
  }))
}

export function SplitCalculatorSync({
  settlementId,
  inviteToken,
  onBack,
}: SplitCalculatorSyncProps) {
  const [paidSettlementsArray, setPaidSettlementsArray] = useState<string[]>([])
  const paidSettlements = useMemo(() => new Set(paidSettlementsArray), [paidSettlementsArray])

  const [paymentModal, setPaymentModal] = useState<{
    isOpen: boolean
    lud16: string
    recipientName: string
    recipientPicture?: string
    amount: number
  }>({
    isOpen: false,
    lud16: '',
    recipientName: '',
    recipientPicture: undefined,
    amount: 0,
  })

  const {
    btcPrice,
    loading: priceLoading,
    error: priceError,
    rateLimited: priceRateLimited,
    refetch: refetchPrice,
  } = useBtcPrice()

  // Sync with Nostr
  const {
    state,
    isOwner,
    isLoading,
    error: syncError,
    connectionStatus,
    addMember,
    addExpense,
    lockSettlement,
  } = useSettlementSync({
    settlementId,
    inviteToken,
  })

  // Convert state to UI types
  const members = useMemo(() => stateToMembers(state), [state])
  const expenses = useMemo(() => stateToExpenses(state), [state])

  const settlementName = state?.name || '精算'
  const settlementCurrency = (state?.currency?.toLowerCase() || 'jpy') as Currency
  const isLocked = state?.isLocked || false

  const { currency, setCurrency, formatCurrency, currencySymbol, fiatToSats, formatBtcPrice } =
    useCurrency(btcPrice, settlementCurrency, () => {})

  // Calculate settlements
  const { totalAmount, perPerson, settlements, getMemberPaidTotal } = useMemo(() => {
    if (members.length === 0 || expenses.length === 0) {
      return {
        totalAmount: 0,
        perPerson: 0,
        settlements: [],
        getMemberPaidTotal: () => 0,
      }
    }

    const total = expenses.reduce((sum, e) => sum + e.amount, 0)
    const perMember = total / members.length

    // Calculate how much each member paid
    const paid: Record<string, number> = {}
    members.forEach((m) => {
      paid[m.id] = 0
    })
    expenses.forEach((e) => {
      if (paid[e.paidById] !== undefined) {
        paid[e.paidById] += e.amount
      }
    })

    // Calculate balances (positive = should receive, negative = should pay)
    const balances: Record<string, number> = {}
    members.forEach((m) => {
      balances[m.id] = paid[m.id] - perMember
    })

    // Generate settlements
    const settlementsList: Settlement[] = []
    const debtors = members
      .filter((m) => balances[m.id] < -0.01)
      .map((m) => ({ ...m, balance: balances[m.id] }))
    const creditors = members
      .filter((m) => balances[m.id] > 0.01)
      .map((m) => ({ ...m, balance: balances[m.id] }))

    debtors.sort((a, b) => a.balance - b.balance)
    creditors.sort((a, b) => b.balance - a.balance)

    let i = 0
    let j = 0
    while (i < debtors.length && j < creditors.length) {
      const debtor = debtors[i]
      const creditor = creditors[j]
      const amount = Math.min(-debtor.balance, creditor.balance)

      if (amount > 0.01) {
        settlementsList.push({
          id: `${debtor.id}-${creditor.id}`,
          from: debtor.id,
          to: creditor.id,
          amount: Math.round(amount),
        })
      }

      debtor.balance += amount
      creditor.balance -= amount

      if (Math.abs(debtor.balance) < 0.01) i++
      if (Math.abs(creditor.balance) < 0.01) j++
    }

    return {
      totalAmount: total,
      perPerson: perMember,
      settlements: settlementsList,
      getMemberPaidTotal: (memberId: string) => paid[memberId] || 0,
    }
  }, [members, expenses])

  // Generate invite link
  const inviteLink = useMemo(() => {
    if (typeof window === 'undefined') return ''
    return generateInviteLink(settlementId, inviteToken, window.location.origin)
  }, [settlementId, inviteToken])

  // Handlers
  const handleAddMember = useCallback(
    async (member: Member) => {
      await addMember(member.id, member.name)
    },
    [addMember]
  )

  const handleRemoveMember = useCallback((id: string) => {
    // In sync mode, we cannot remove members (append-only)
    console.warn('Cannot remove members in sync mode')
  }, [])

  const handleAddExpense = useCallback(
    async (expense: Expense) => {
      await addExpense(
        expense.paidById,
        expense.amount,
        expense.currency.toUpperCase(),
        expense.description
      )
    },
    [addExpense]
  )

  const handleRemoveExpense = useCallback((id: string) => {
    // In sync mode, we cannot remove expenses (append-only)
    // Instead, add a negative expense for correction
    console.warn('Cannot remove expenses in sync mode. Use negative amount for corrections.')
  }, [])

  const handleTogglePaid = useCallback((settlementId: string) => {
    setPaidSettlementsArray((prev) => {
      if (prev.includes(settlementId)) {
        return prev.filter((id) => id !== settlementId)
      }
      return [...prev, settlementId]
    })
  }, [])

  const handleOpenLightningPayment = useCallback(
    (settlement: Settlement) => {
      const recipient = members.find((m) => m.id === settlement.to)
      if (recipient?.nostrProfile?.lud16) {
        setPaymentModal({
          isOpen: true,
          lud16: recipient.nostrProfile.lud16,
          recipientName: recipient.name,
          recipientPicture: recipient.nostrProfile.picture,
          amount: fiatToSats(settlement.amount),
        })
      }
    },
    [members, fiatToSats]
  )

  const handleLock = useCallback(
    async (acceptedEventIds: string[]) => {
      await lockSettlement(acceptedEventIds)
    },
    [lockSettlement]
  )

  // Prepare expenses for lock dialog
  const expensesForLock = useMemo(() => {
    return expenses.map((e) => {
      const member = members.find((m) => m.id === e.paidById)
      const invalidExpense = state?.invalidExpenses?.find((inv) => inv.eventId === e.id)
      return {
        id: e.id,
        description: e.description,
        amount: e.amount,
        memberName: member?.name || 'Unknown',
        isValid: !invalidExpense,
        invalidReason: invalidExpense?.reason,
      }
    })
  }, [expenses, members, state?.invalidExpenses])

  // Loading state
  if (isLoading) {
    return (
      <div className="min-h-screen bg-background p-4 md:p-8">
        <div className="mx-auto max-w-2xl">
          <div className="flex min-h-[50vh] items-center justify-center">
            <p className="text-muted-foreground">読み込み中...</p>
          </div>
        </div>
      </div>
    )
  }

  const connectionStatusMap: Record<string, ConnectionStatus> = {
    connecting: 'connecting',
    connected: 'connected',
    disconnected: 'disconnected',
    error: 'error',
  }

  return (
    <div className="min-h-screen bg-background p-4 md:p-8">
      <div className="mx-auto max-w-2xl">
        <div className="mb-4">
          <Button variant="ghost" onClick={onBack} className="gap-2">
            <ArrowLeft className="h-4 w-4" />
            戻る
          </Button>
        </div>

        <SettlementHeader
          name={settlementName}
          isOwner={isOwner}
          isLocked={isLocked}
          inviteLink={inviteLink}
          connectionStatus={connectionStatusMap[connectionStatus] || 'disconnected'}
          onNameChange={undefined} // Name change requires republishing settlement event
        />

        {syncError && (
          <Alert className="mb-6 border-destructive bg-destructive/10">
            <AlertTriangle className="h-4 w-4 text-destructive" />
            <AlertDescription className="text-destructive">{syncError}</AlertDescription>
          </Alert>
        )}

        {!isLocked && (
          <>
            <MemberList
              members={members}
              onAddMember={handleAddMember}
              onRemoveMember={handleRemoveMember}
              formatCurrency={formatCurrency}
              getMemberPaidTotal={getMemberPaidTotal}
            />

            <ExpenseForm
              members={members}
              onAddExpense={handleAddExpense}
              currency={currency}
              currencySymbol={currencySymbol}
            />
          </>
        )}

        <ExpenseList
          expenses={expenses}
          members={members}
          currentCurrency={currency}
          onRemoveExpense={handleRemoveExpense}
          formatCurrency={formatCurrency}
        />

        {members.length > 0 && expenses.length > 0 && (
          <Card className="mb-6 border-2 border-border">
            <CardContent className="py-6">
              <div className="grid grid-cols-2 gap-4 text-center">
                <div>
                  <p className="text-sm font-medium uppercase tracking-wide text-muted-foreground">
                    合計金額
                  </p>
                  <p className="mt-1 text-2xl font-bold text-foreground">
                    {formatCurrency(totalAmount)}
                  </p>
                </div>
                <div>
                  <p className="text-sm font-medium uppercase tracking-wide text-muted-foreground">
                    1人あたり
                  </p>
                  <p className="mt-1 text-2xl font-bold text-foreground">
                    {formatCurrency(Math.round(perPerson))}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        <SettlementList
          settlements={settlements}
          members={members}
          paidSettlements={paidSettlements}
          onTogglePaid={handleTogglePaid}
          onOpenLightningPayment={handleOpenLightningPayment}
          formatCurrency={formatCurrency}
          fiatToSats={fiatToSats}
        />

        {members.length === 0 && (
          <Card className="border-2 border-dashed border-muted">
            <CardContent className="py-12 text-center">
              <Users className="mx-auto h-12 w-12 text-muted-foreground/50" />
              <p className="mt-4 text-muted-foreground">まずメンバーを追加してください</p>
            </CardContent>
          </Card>
        )}

        {members.length > 0 && expenses.length === 0 && (
          <Card className="border-2 border-dashed border-muted">
            <CardContent className="py-12 text-center">
              <Receipt className="mx-auto h-12 w-12 text-muted-foreground/50" />
              <p className="mt-4 text-muted-foreground">支出を追加すると精算結果が表示されます</p>
            </CardContent>
          </Card>
        )}

        {isOwner && !isLocked && expenses.length > 0 && (
          <div className="mt-6">
            <LockSettlementDialog
              expenses={expensesForLock}
              onLock={handleLock}
              formatCurrency={formatCurrency}
            />
          </div>
        )}

        <div className="mt-8 flex justify-center">
          <CurrencySwitcher currency={currency} onCurrencyChange={setCurrency} />
        </div>

        <PriceFooter
          formattedBtcPrice={formatBtcPrice()}
          loading={priceLoading}
          error={priceError}
          rateLimited={priceRateLimited}
          onRefresh={refetchPrice}
        />
      </div>

      <LightningPaymentModal
        isOpen={paymentModal.isOpen}
        onClose={() => setPaymentModal({ ...paymentModal, isOpen: false })}
        lud16={paymentModal.lud16}
        recipientName={paymentModal.recipientName}
        recipientPicture={paymentModal.recipientPicture}
        suggestedAmount={paymentModal.amount}
        currency={currency}
        btcPrice={btcPrice}
      />
    </div>
  )
}

// src/lib/components/split-calculator-sync.svelte
<script lang="ts">
  import { SettlementSync, generateInviteLink, parseInviteLink, createSettlement } from '$lib/stores/settlement-sync.svelte'
  import { btcPriceStore } from '$lib/stores/btc-price.svelte'
  import ExpenseForm from './expense-form.svelte'
  import ExpenseList from './expense-list.svelte'
  import SettlementList from './settlement-list.svelte'
  import MemberList from './member-list.svelte'
  import CurrencySwitcher from './currency-switcher.svelte'
  import SyncStatusIndicator from './sync-status-indicator.svelte'
  import SettlementHeader from './settlement-header.svelte'
  import LockSettlementDialog from './lock-settlement-dialog.svelte'
  import CreateSettlementDialog from './create-settlement-dialog.svelte'
  import LightningPaymentModal from './lightning-payment-modal.svelte'
  import PriceFooter from './price-footer.svelte'
  import { generateSettlementId } from '$lib/nostr/settlement/id'
  import { DEFAULT_RELAYS } from '$lib/constants'
  import { browser } from '$app/environment'
  import { goto } from '$app/navigation'
  import { calculateSettlements } from '$lib/settlements'
  import type { Currency } from '$lib/types/split-calculator'

  let { initialSettlementId = null, initialInviteToken = null }: {
    initialSettlementId?: string | null
    initialInviteToken?: string | null
  } = $props()

  let settlementId = $state<string | null>(initialSettlementId)
  let inviteToken = $state<string | null>(initialInviteToken)
  let sync = $state<SettlementSync | null>(null)
  let currency = $state<Currency>('jpy')
  let showCreateDialog = $state(false)
  let showLockDialog = $state(false)
  let lightningPayTarget = $state<{ fromMemberId: string; toMemberId: string; amount: number } | null>(null)
  let baseUrl = $state(browser ? window.location.origin + window.location.pathname : '')

  $effect(() => {
    if (settlementId && inviteToken) {
      sync = new SettlementSync({ settlementId, inviteToken })
    }
  })

  $effect(() => {
    btcPriceStore.fetchBtcPrice()
  })

  const syncMembers = $derived(
    (sync?.state?.members ?? []).map(m => ({
      id: m.pubkey,
      name: m.name ?? m.pubkey.slice(0, 8),
      npub: undefined,
      nostrProfile: m.picture ? { picture: m.picture, lud16: m.lud16 } : undefined,
    }))
  )

  const syncExpenses = $derived(
    (sync?.state?.expenses ?? []).map(e => ({
      id: e.eventId,
      description: e.note,
      amount: e.amount,
      paidById: e.memberPubkey,
      currency: (e.currency as Currency) ?? 'jpy',
    }))
  )

  async function handleCreate(name: string, cur: Currency) {
    const sid = generateSettlementId()
    const token = Array.from(crypto.getRandomValues(new Uint8Array(16)))
      .map(b => b.toString(16).padStart(2, '0'))
      .join('')
    await createSettlement({ settlementId: sid, inviteToken: token, name, currency: cur, relays: [...DEFAULT_RELAYS] })
    settlementId = sid
    inviteToken = token
    showCreateDialog = false
    if (browser) {
      const url = new URL(window.location.href)
      url.searchParams.set('s', sid)
      url.searchParams.set('t', token)
      window.history.pushState({}, '', url.toString())
    }
  }

  async function handleAddMember(name: string) {
    if (!sync) return
    throw new Error('同期モードでは npub を入力してメンバーを追加してください')
  }
</script>

<div class="min-h-screen bg-gray-100 dark:bg-gray-950 flex flex-col">
  {#if !settlementId || !inviteToken}
    <!-- No session state -->
    <div class="flex-1 flex flex-col items-center justify-center gap-6 px-4">
      <div class="text-center">
        <h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-2">
          ワリカンさん (同期モード)
        </h1>
        <p class="text-gray-500 dark:text-gray-400 text-sm">
          セッションがありません
        </p>
      </div>
      <button
        type="button"
        onclick={() => { showCreateDialog = true }}
        class="rounded-xl bg-blue-500 hover:bg-blue-600 text-white px-6 py-3 text-sm font-semibold transition-colors shadow-sm"
      >
        新しいセッションを作成
      </button>
    </div>
  {:else}
    <!-- Header -->
    <header class="bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800 sticky top-0 z-10">
      <div class="max-w-lg mx-auto px-4 py-3 flex flex-col gap-2">
        <div class="flex items-center justify-between gap-4">
          <div class="flex-1 min-w-0">
            <SettlementHeader
              settlementName={sync?.state?.name ?? 'Loading...'}
              settlementId={settlementId}
              inviteToken={inviteToken}
              baseUrl={baseUrl}
            />
          </div>
          <CurrencySwitcher
            currency={currency}
            oncurrencychange={(c) => { currency = c }}
          />
        </div>
        <div class="flex items-center gap-2">
          {#if sync}
            <SyncStatusIndicator status={sync.connectionStatus} />
          {/if}
        </div>
      </div>
    </header>

    <!-- Main content -->
    <main class="flex-1 max-w-lg mx-auto w-full px-4 py-5 flex flex-col gap-4">
      {#if sync?.isLoading}
        <div class="flex items-center justify-center py-12">
          <svg class="animate-spin w-8 h-8 text-blue-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path>
          </svg>
        </div>
      {/if}

      {#if sync?.error}
        <div class="rounded-xl bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-700 px-4 py-3">
          <p class="text-sm font-medium text-red-800 dark:text-red-300">
            エラー: {sync.error}
          </p>
        </div>
      {/if}

      <!-- Card: Members -->
      <section class="rounded-2xl bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 p-5 shadow-sm">
        <h2 class="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3">
          メンバー
        </h2>
        <MemberList
          members={syncMembers}
          isOwner={sync?.isOwner ?? false}
          onadd={handleAddMember}
          onremove={async () => {}}
        />
      </section>

      <!-- Card: Add expense -->
      <section class="rounded-2xl bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 p-5 shadow-sm">
        <h2 class="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3">
          支出を追加
        </h2>
        <ExpenseForm
          members={syncMembers}
          currency={currency}
          onadd={async (e) => {
            if (sync) await sync.addExpense(e.paidById, e.amount, e.currency, e.description)
          }}
        />
      </section>

      <!-- Card: Expense list -->
      <section class="rounded-2xl bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 p-5 shadow-sm">
        <h2 class="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3">
          支出一覧
        </h2>
        <ExpenseList
          expenses={syncExpenses}
          members={syncMembers}
          currency={currency}
          btcPrice={btcPriceStore.btcPrice}
          onremove={() => {}}
        />
      </section>

      <!-- Card: Settlements -->
      <section class="rounded-2xl bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 p-5 shadow-sm">
        <h2 class="text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3">
          精算
        </h2>
        <SettlementList
          result={calculateSettlements(syncMembers, syncExpenses)}
          members={syncMembers}
          onpay={(from, to, amount) => { lightningPayTarget = { fromMemberId: from, toMemberId: to, amount } }}
        />
      </section>

      <!-- Lock settlement button (owner only, not yet locked) -->
      {#if sync?.isOwner && !sync?.isLocked}
        <div class="flex justify-center pt-2 pb-4">
          <button
            type="button"
            onclick={() => { showLockDialog = true }}
            class="rounded-xl bg-red-500 hover:bg-red-600 text-white px-6 py-3 text-sm font-semibold transition-colors shadow-sm"
          >
            精算を確定する
          </button>
        </div>
      {/if}
    </main>

    <!-- Footer -->
    <footer class="max-w-lg mx-auto w-full">
      <PriceFooter
        btcPrice={btcPriceStore.btcPrice}
        currency={currency}
      />
    </footer>
  {/if}
</div>

<!-- Dialogs -->
<CreateSettlementDialog
  isOpen={showCreateDialog}
  oncreate={handleCreate}
  onclose={() => { showCreateDialog = false }}
/>

{#if sync}
  <LockSettlementDialog
    isOpen={showLockDialog}
    expenseEventIds={sync.state?.expenses.map(e => e.eventId) ?? []}
    onlock={async (ids) => { await sync!.lockSettlement(ids); showLockDialog = false }}
    onclose={() => { showLockDialog = false }}
  />
{/if}

<LightningPaymentModal
  isOpen={!!lightningPayTarget}
  toMember={syncMembers.find(m => m.id === lightningPayTarget?.toMemberId) ?? null}
  amount={lightningPayTarget?.amount ?? 0}
  currency={currency}
  btcPrice={btcPriceStore.btcPrice}
  onclose={() => { lightningPayTarget = null }}
/>
