// components/split-calculator/sync-status-indicator.tsx
"use client"

import React from "react"

import { Wifi, WifiOff, Loader2, AlertCircle } from "lucide-react"
import { cn } from "@/lib/utils"
import type { ConnectionStatus } from "@/lib/nostr/settlement/hooks"

export type { ConnectionStatus }

interface SyncStatusIndicatorProps {
  status: ConnectionStatus
  className?: string
}

const statusConfig: Record<
  ConnectionStatus,
  { icon: React.ElementType; label: string; color: string }
> = {
  connecting: {
    icon: Loader2,
    label: "接続中...",
    color: "text-amber-500",
  },
  connected: {
    icon: Wifi,
    label: "接続済み",
    color: "text-green-500",
  },
  disconnected: {
    icon: WifiOff,
    label: "未接続",
    color: "text-muted-foreground",
  },
  error: {
    icon: AlertCircle,
    label: "接続エラー",
    color: "text-destructive",
  },
}

export function SyncStatusIndicator({ status, className }: SyncStatusIndicatorProps) {
  const config = statusConfig[status]
  const Icon = config.icon

  return (
    <div
      className={cn("flex items-center gap-1 text-xs", config.color, className)}
      role="status"
      aria-live="polite"
    >
      <Icon
        className={cn("h-3 w-3", status === "connecting" && "animate-spin")}
        aria-hidden="true"
      />
      <span>{config.label}</span>
    </div>
  )
}

// src/lib/components/sync-status-indicator.svelte
<script lang="ts">
  import type { ConnectionStatus } from '$lib/stores/settlement-sync.svelte'

  let {
    status
  }: {
    status: ConnectionStatus
  } = $props()

  const statusConfig: Record<ConnectionStatus, { dotClass: string; label: string }> = {
    connecting: { dotClass: 'bg-yellow-400', label: '接続中...' },
    connected: { dotClass: 'bg-green-500', label: '接続済み' },
    disconnected: { dotClass: 'bg-gray-400', label: '未接続' },
    error: { dotClass: 'bg-red-500', label: 'エラー' }
  }

  let config = $derived(statusConfig[status])
</script>

<div class="inline-flex items-center gap-1.5">
  <span class="inline-block w-2 h-2 rounded-full flex-shrink-0 {config.dotClass}"></span>
  <span class="text-sm text-gray-600 dark:text-gray-400">{config.label}</span>
</div>
