// src/lib/components/member-avatar.svelte
<script lang="ts">
  import type { Member } from '$lib/types/split-calculator'

  let {
    member,
    size = 'md'
  }: {
    member: Member
    size?: 'sm' | 'md' | 'lg'
  } = $props()

  const sizeMap = {
    sm: 'w-6 h-6 text-xs',
    md: 'w-8 h-8 text-sm',
    lg: 'w-12 h-12 text-base'
  }

  const pixelMap = {
    sm: 24,
    md: 32,
    lg: 48
  }

  let sizeClass = $derived(sizeMap[size])
  let pixelSize = $derived(pixelMap[size])
  let picture = $derived(member.nostrProfile?.picture)
  let initial = $derived(member.name ? member.name.charAt(0) : '?')
</script>

<div
  class="relative inline-flex items-center justify-center rounded-full overflow-hidden bg-gray-200 dark:bg-gray-600 flex-shrink-0 {sizeClass}"
  style="width: {pixelSize}px; height: {pixelSize}px;"
  title={member.name}
>
  {#if picture}
    <img
      src={picture}
      alt={member.name}
      class="w-full h-full object-cover"
      width={pixelSize}
      height={pixelSize}
    />
  {:else}
    <span class="font-medium text-gray-600 dark:text-gray-200 leading-none select-none">
      {initial}
    </span>
  {/if}
</div>

// components/split-calculator/member-avatar.tsx
'use client'

import Image from 'next/image'
import { useState } from 'react'
import type { Member } from '@/types/split-calculator'

interface MemberAvatarProps {
  member: Member
  size?: number
}

export function MemberAvatar({ member, size = 32 }: MemberAvatarProps) {
  const [imageError, setImageError] = useState(false)
  const initials = member.name.slice(0, 2)

  if (member.nostrProfile?.picture && !imageError) {
    return (
      <div
        className="relative shrink-0 overflow-hidden rounded-full border-2 border-border"
        style={{ width: size, height: size }}
      >
        <Image
          src={member.nostrProfile.picture || '/placeholder.svg'}
          alt={`${member.name}のアバター`}
          fill
          sizes={`${size}px`}
          className="object-cover"
          onError={() => setImageError(true)}
          unoptimized
        />
      </div>
    )
  }

  return (
    <div
      className="flex shrink-0 items-center justify-center rounded-full bg-secondary text-xs font-medium text-secondary-foreground"
      style={{ width: size, height: size }}
      role="img"
      aria-label={`${member.name}のアバター`}
    >
      {initials}
    </div>
  )
}
