// src/lib/components/MemberList.svelte
<script lang="ts">
  import { Loader2, Trash2, UserPlus, Users, Zap } from 'lucide-svelte'
  import { isValidNpub, fetchNostrProfile } from '$lib/nostr/profile-rx'
  import type { Member } from '$lib/types/split-calculator'
  import MemberAvatar from './MemberAvatar.svelte'

  interface Props {
    members: Member[]
    onAddMember: (member: Member) => void | Promise<void>
    onRemoveMember: (id: string) => void
    formatCurrency: (amount: number) => string
    getMemberPaidTotal: (memberId: string) => number
  }

  let { members, onAddMember, onRemoveMember, formatCurrency, getMemberPaidTotal }: Props =
    $props()

  let addMode = $state<'name' | 'nostr'>('name')
  let newName = $state('')
  let newNpub = $state('')
  let loadingNostr = $state(false)
  let nostrError = $state<string | null>(null)
  let confirmDeleteId = $state<string | null>(null)

  function addByName() {
    if (!newName.trim()) return
    onAddMember({ id: crypto.randomUUID(), name: newName.trim() })
    newName = ''
  }

  async function addByNostr() {
    if (!newNpub.trim()) return
    if (!isValidNpub(newNpub.trim())) {
      nostrError = '無効なnpubです。npub1...の形式で入力してください'
      return
    }
    if (members.some((m) => m.npub === newNpub.trim())) {
      nostrError = 'このNostrユーザーは既に登録されています'
      return
    }

    loadingNostr = true
    nostrError = null
    const npub = newNpub.trim()

    try {
      const profile = await fetchNostrProfile(npub)
      if (profile) {
        await onAddMember({
          id: crypto.randomUUID(),
          name: profile.displayName || profile.name || 'Nostr User',
          npub,
          nostrProfile: profile,
        })
        newNpub = ''
      } else {
        nostrError = 'プロフィールを取得できませんでした'
      }
    } catch {
      nostrError = 'プロフィールの取得中にエラーが発生しました'
    } finally {
      loadingNostr = false
    }
  }
</script>

<div class="mb-6 rounded-xl border-2 border-gray-200 bg-white">
  <div class="border-b border-gray-100 px-4 py-3">
    <h2 class="flex items-center gap-2 font-semibold text-gray-800">
      <Users class="h-5 w-5 text-blue-600" />
      メンバー ({members.length}人)
    </h2>
  </div>
  <div class="p-4">
    <!-- Tab switcher -->
    <div class="mb-4 grid grid-cols-2 gap-1 rounded-lg bg-gray-100 p-1">
      <button
        onclick={() => {
          addMode = 'name'
          nostrError = null
        }}
        class="rounded-md py-1.5 text-sm font-medium {addMode === 'name'
          ? 'bg-white text-gray-900 shadow-sm'
          : 'text-gray-500'}"
      >
        名前で追加
      </button>
      <button
        onclick={() => {
          addMode = 'nostr'
          nostrError = null
        }}
        class="rounded-md py-1.5 text-sm font-medium {addMode === 'nostr'
          ? 'bg-white text-gray-900 shadow-sm'
          : 'text-gray-500'}"
      >
        Nostrで追加
      </button>
    </div>

    {#if addMode === 'name'}
      <div class="flex gap-2">
        <input
          type="text"
          placeholder="名前を入力"
          bind:value={newName}
          onkeydown={(e) => e.key === 'Enter' && addByName()}
          class="flex-1 rounded-lg border-2 border-gray-200 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
        />
        <button
          onclick={addByName}
          disabled={!newName.trim()}
          class="flex shrink-0 items-center gap-1 rounded-lg bg-blue-600 px-3 py-2 text-sm text-white hover:bg-blue-700 disabled:opacity-40"
        >
          <UserPlus class="h-4 w-4" />
          追加
        </button>
      </div>
    {:else}
      <div class="space-y-2">
        <div class="flex gap-2">
          <input
            type="text"
            placeholder="npub1..."
            bind:value={newNpub}
            oninput={() => (nostrError = null)}
            onkeydown={(e) => e.key === 'Enter' && addByNostr()}
            class="flex-1 rounded-lg border-2 border-gray-200 px-3 py-2 font-mono text-sm focus:border-blue-500 focus:outline-none {nostrError
              ? 'border-red-400'
              : ''}"
          />
          <button
            onclick={addByNostr}
            disabled={!newNpub.trim() || loadingNostr}
            class="flex shrink-0 items-center gap-1 rounded-lg bg-blue-600 px-3 py-2 text-sm text-white hover:bg-blue-700 disabled:opacity-40"
          >
            {#if loadingNostr}
              <Loader2 class="h-4 w-4 animate-spin" />
            {:else}
              <UserPlus class="h-4 w-4" />
            {/if}
            追加
          </button>
        </div>
        {#if nostrError}
          <p class="text-sm text-red-500" role="alert">{nostrError}</p>
        {:else}
          <p class="text-xs text-gray-400">npubを入力するとプロフィール情報を自動取得します</p>
        {/if}
      </div>
    {/if}

    {#if members.length > 0}
      <ul class="mt-4 space-y-2">
        {#each members as member (member.id)}
          <li
            class="flex items-center justify-between rounded-lg border border-gray-100 bg-gray-50 p-3"
          >
            <div class="flex min-w-0 flex-1 items-center gap-3">
              <MemberAvatar {member} />
              <div class="min-w-0 flex-1">
                <div class="flex items-center gap-1.5">
                  <span class="truncate text-sm font-medium text-gray-800">{member.name}</span>
                  {#if member.nostrProfile?.lud16}
                    <Zap class="h-3.5 w-3.5 shrink-0 text-amber-500" />
                  {/if}
                </div>
                <span class="text-xs text-gray-400">
                  支払: {formatCurrency(getMemberPaidTotal(member.id))}
                </span>
              </div>
            </div>
            <button
              onclick={() => (confirmDeleteId = member.id)}
              class="ml-2 rounded p-1 text-gray-400 hover:text-red-500"
              aria-label="{member.name}を削除"
            >
              <Trash2 class="h-4 w-4" />
            </button>
          </li>
        {/each}
      </ul>
    {/if}
  </div>
</div>

<!-- Confirm delete dialog -->
{#if confirmDeleteId !== null}
  {@const target = members.find((m) => m.id === confirmDeleteId)}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
    onclick={() => (confirmDeleteId = null)}
    onkeydown={(e) => e.key === 'Escape' && (confirmDeleteId = null)}
    role="dialog"
    tabindex="-1"
    aria-modal="true"
  >
    <div
      class="mx-4 w-full max-w-sm rounded-xl bg-white p-6 shadow-xl"
      onclick={(e) => e.stopPropagation()}
    >
      <h3 class="mb-2 font-semibold text-gray-900">メンバーを削除しますか？</h3>
      <p class="mb-6 text-sm text-gray-500">
        {target?.name}をメンバーから削除します。この操作によりこのメンバーの支出も削除されます。
      </p>
      <div class="flex gap-3">
        <button
          onclick={() => (confirmDeleteId = null)}
          class="flex-1 rounded-lg border-2 border-gray-200 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
        >
          キャンセル
        </button>
        <button
          onclick={() => {
            if (confirmDeleteId) onRemoveMember(confirmDeleteId)
            confirmDeleteId = null
          }}
          class="flex-1 rounded-lg bg-red-600 py-2 text-sm font-medium text-white hover:bg-red-700"
        >
          削除する
        </button>
      </div>
    </div>
  </div>
{/if}

// components/split-calculator/member-list.tsx
'use client'

import { Loader2, Trash2, UserPlus, Users, Zap } from 'lucide-react'
import { useState } from 'react'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { fetchNostrProfile, isValidNpub } from '@/lib/nostr/index'
import type { Member } from '@/types/split-calculator'
import { MemberAvatar } from './member-avatar'

interface MemberListProps {
  members: Member[]
  onAddMember: (member: Member) => void
  onRemoveMember: (id: string) => void
  formatCurrency: (amount: number) => string
  getMemberPaidTotal: (memberId: string) => number
}

export function MemberList({
  members,
  onAddMember,
  onRemoveMember,
  formatCurrency,
  getMemberPaidTotal,
}: MemberListProps) {
  const [addMemberMode, setAddMemberMode] = useState<'name' | 'nostr'>('name')
  const [newMemberName, setNewMemberName] = useState('')
  const [newMemberNpub, setNewMemberNpub] = useState('')
  const [loadingNostr, setLoadingNostr] = useState(false)
  const [nostrError, setNostrError] = useState<string | null>(null)

  const addMemberByName = () => {
    if (newMemberName.trim()) {
      onAddMember({
        id: crypto.randomUUID(),
        name: newMemberName.trim(),
      })
      setNewMemberName('')
    }
  }

  const addMemberByNostr = async () => {
    if (!newMemberNpub.trim()) return

    if (!isValidNpub(newMemberNpub.trim())) {
      setNostrError('無効なnpubです。npub1...の形式で入力してください')
      return
    }

    if (members.some((m) => m.npub === newMemberNpub.trim())) {
      setNostrError('このNostrユーザーは既に登録されています')
      return
    }

    setLoadingNostr(true)
    setNostrError(null)

    let isCancelled = false
    const npubToFetch = newMemberNpub.trim()

    try {
      const profile = await fetchNostrProfile(npubToFetch)

      // Check if component is still mounted and npub hasn't changed
      if (isCancelled) return

      if (profile) {
        const displayName = profile.displayName || profile.name || 'Nostr User'
        onAddMember({
          id: crypto.randomUUID(),
          name: displayName,
          npub: npubToFetch,
          nostrProfile: profile,
        })
        setNewMemberNpub('')
      } else {
        setNostrError(
          'プロフィールを取得できませんでした。リレーに接続できないか、プロフィールが設定されていない可能性があります'
        )
      }
    } catch {
      if (!isCancelled) {
        setNostrError('プロフィールの取得中にエラーが発生しました')
      }
    } finally {
      if (!isCancelled) {
        setLoadingNostr(false)
      }
    }

    return () => {
      isCancelled = true
    }
  }

  return (
    <Card className="mb-6 border-2 border-border">
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-lg">
          <Users className="h-5 w-5 text-primary" />
          メンバー ({members.length}人)
        </CardTitle>
      </CardHeader>
      <CardContent>
        <Tabs value={addMemberMode} onValueChange={(v) => setAddMemberMode(v as 'name' | 'nostr')}>
          <TabsList className="mb-4 grid w-full grid-cols-2">
            <TabsTrigger value="name">名前で追加</TabsTrigger>
            <TabsTrigger value="nostr">Nostrで追加</TabsTrigger>
          </TabsList>
          <TabsContent value="name">
            <div className="space-y-2">
              <Label htmlFor="member-name" className="sr-only">
                メンバー名
              </Label>
              <div className="flex gap-2">
                <Input
                  id="member-name"
                  placeholder="名前を入力"
                  value={newMemberName}
                  onChange={(e) => setNewMemberName(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && addMemberByName()}
                  className="border-2"
                  aria-describedby="member-name-hint"
                />
                <Button
                  onClick={addMemberByName}
                  disabled={!newMemberName.trim()}
                  className="shrink-0 bg-primary text-primary-foreground hover:bg-primary/90"
                  aria-label="メンバーを追加"
                >
                  <UserPlus className="mr-1 h-4 w-4" aria-hidden="true" />
                  追加
                </Button>
              </div>
              <p id="member-name-hint" className="sr-only">
                Enterキーでも追加できます
              </p>
            </div>
          </TabsContent>
          <TabsContent value="nostr">
            <div className="space-y-3">
              <Label htmlFor="member-npub" className="sr-only">
                Nostr公開鍵
              </Label>
              <div className="flex gap-2">
                <Input
                  id="member-npub"
                  placeholder="npub1..."
                  value={newMemberNpub}
                  onChange={(e) => {
                    setNewMemberNpub(e.target.value)
                    setNostrError(null)
                  }}
                  onKeyDown={(e) => e.key === 'Enter' && addMemberByNostr()}
                  className="border-2 font-mono text-sm"
                  aria-describedby={nostrError ? 'nostr-error nostr-hint' : 'nostr-hint'}
                  aria-invalid={nostrError ? 'true' : undefined}
                />
                <Button
                  onClick={addMemberByNostr}
                  disabled={!newMemberNpub.trim() || loadingNostr}
                  className="shrink-0 bg-primary text-primary-foreground hover:bg-primary/90"
                  aria-label={loadingNostr ? '読み込み中' : 'Nostrメンバーを追加'}
                >
                  {loadingNostr ? (
                    <Loader2 className="mr-1 h-4 w-4 animate-spin" aria-hidden="true" />
                  ) : (
                    <UserPlus className="mr-1 h-4 w-4" aria-hidden="true" />
                  )}
                  追加
                </Button>
              </div>
              {nostrError && (
                <p id="nostr-error" className="text-sm text-destructive" role="alert">
                  {nostrError}
                </p>
              )}
              <p id="nostr-hint" className="text-xs text-muted-foreground">
                npubを入力するとプロフィール情報を自動取得します
              </p>
            </div>
          </TabsContent>
        </Tabs>

        {members.length > 0 && (
          <div className="mt-4 space-y-2">
            {members.map((member) => (
              <div
                key={member.id}
                className="flex items-center justify-between rounded-lg border-2 border-border bg-secondary/30 p-3"
              >
                <div className="flex min-w-0 flex-1 items-center gap-3">
                  <MemberAvatar member={member} />
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <span className="truncate font-medium text-foreground">{member.name}</span>
                      {member.nostrProfile?.lud16 && (
                        <Zap className="h-4 w-4 shrink-0 text-amber-500" />
                      )}
                    </div>
                    <span className="text-xs text-muted-foreground">
                      支払: {formatCurrency(getMemberPaidTotal(member.id))}
                    </span>
                  </div>
                </div>
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8 text-muted-foreground hover:text-destructive"
                      aria-label={`${member.name}を削除`}
                    >
                      <Trash2 className="h-4 w-4" aria-hidden="true" />
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>メンバーを削除しますか？</AlertDialogTitle>
                      <AlertDialogDescription>
                        {member.name}
                        をメンバーから削除します。この操作により、このメンバーが支払った支出も削除されます。
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>キャンセル</AlertDialogCancel>
                      <AlertDialogAction
                        onClick={() => onRemoveMember(member.id)}
                        className="bg-destructive text-white hover:bg-destructive/90"
                      >
                        削除する
                      </AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  )
}
