// src/lib/components/PriceFooter.svelte
<script lang="ts">
  import { RefreshCw } from 'lucide-svelte'

  interface Props {
    formattedBtcPrice: string
    loading: boolean
    error: string | null
    rateLimited: boolean
    onRefresh: () => void
  }

  let { formattedBtcPrice, loading, error, rateLimited, onRefresh }: Props = $props()
</script>

<div class="mt-8 text-center text-xs text-gray-400">
  {#if error}
    <p class="text-red-400">
      {rateLimited ? 'レート制限中。しばらくお待ちください' : 'BTC価格の取得に失敗'}
    </p>
  {:else}
    <p>BTC: {formattedBtcPrice}</p>
  {/if}
  <button
    onclick={onRefresh}
    disabled={loading || rateLimited}
    class="mt-1 inline-flex items-center gap-1 text-gray-400 hover:text-gray-300 disabled:opacity-40"
    aria-label="BTC価格を更新"
  >
    <RefreshCw class="h-3 w-3 {loading ? 'animate-spin' : ''}" />
    更新
  </button>
</div>

// components/split-calculator/price-footer.tsx
"use client"

import { Button } from "@/components/ui/button"
import { RefreshCw, AlertCircle, Clock } from "lucide-react"

interface PriceFooterProps {
  formattedBtcPrice: string
  loading: boolean
  error?: string | null
  rateLimited?: boolean
  onRefresh: () => void
}

export function PriceFooter({
  formattedBtcPrice,
  loading,
  error,
  rateLimited,
  onRefresh,
}: PriceFooterProps) {
  return (
    <footer className="mt-8 border-t border-border pt-6">
      <div className="flex flex-col items-center gap-2 text-center">
        {error ? (
          <div
            className="flex flex-wrap items-center justify-center gap-2 text-sm text-destructive"
            role="alert"
          >
            {rateLimited ? (
              <Clock className="h-4 w-4 shrink-0" aria-hidden="true" />
            ) : (
              <AlertCircle className="h-4 w-4 shrink-0" aria-hidden="true" />
            )}
            <span className="text-center">{error}</span>
            <Button
              variant="outline"
              size="sm"
              className="h-7 gap-1 bg-transparent px-2 text-xs"
              onClick={onRefresh}
              disabled={loading || rateLimited}
              aria-label="価格を再取得"
            >
              <RefreshCw
                className={`h-3 w-3 ${loading ? "animate-spin" : ""}`}
                aria-hidden="true"
              />
              再試行
            </Button>
          </div>
        ) : (
          <div className="flex items-center gap-2">
            <span className="text-sm text-muted-foreground">1 BTC = {formattedBtcPrice}</span>
            <Button
              variant="outline"
              size="sm"
              className="h-7 gap-1 bg-transparent px-2 text-xs"
              onClick={onRefresh}
              disabled={loading}
              aria-label="価格を更新"
            >
              <RefreshCw
                className={`h-3 w-3 ${loading ? "animate-spin" : ""}`}
                aria-hidden="true"
              />
              更新
            </Button>
          </div>
        )}
        <p className="text-xs text-muted-foreground/60">価格データ: CoinGecko API</p>
      </div>
    </footer>
  )
}
