// src/lib/components/SettlementHeader.svelte
<script lang="ts">
  import { Check, Copy, Lock, Share2, Wifi, WifiOff, AlertCircle } from 'lucide-svelte'
  import type { ConnectionStatus } from '$lib/nostr/settlement/settlement-sync.svelte'

  interface Props {
    name: string
    isOwner: boolean
    isLocked: boolean
    inviteLink: string
    connectionStatus: ConnectionStatus
  }

  let { name, isOwner, isLocked, inviteLink, connectionStatus }: Props = $props()

  let copied = $state(false)

  async function copyLink() {
    await navigator.clipboard.writeText(inviteLink)
    copied = true
    setTimeout(() => (copied = false), 2000)
  }

  const statusColor = $derived(
    connectionStatus === 'connected'
      ? 'text-green-500'
      : connectionStatus === 'connecting'
        ? 'text-yellow-500 animate-pulse'
        : connectionStatus === 'error'
          ? 'text-red-500'
          : 'text-gray-400'
  )
  const statusLabel = $derived(
    connectionStatus === 'connected'
      ? '接続中'
      : connectionStatus === 'connecting'
        ? '接続中...'
        : connectionStatus === 'error'
          ? 'エラー'
          : '切断'
  )
</script>

<div class="mb-6 rounded-xl border-2 border-gray-200 bg-white p-4">
  <div class="flex items-start justify-between gap-4">
    <div class="min-w-0 flex-1">
      <div class="flex flex-wrap items-center gap-2">
        <h1 class="truncate text-xl font-bold text-gray-900">{name}</h1>
        {#if isOwner}
          <span class="rounded-full bg-blue-100 px-2 py-0.5 text-xs font-medium text-blue-700"
            >オーナー</span
          >
        {/if}
        {#if isLocked}
          <span class="flex items-center gap-1 rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-600">
            <Lock class="h-3 w-3" />
            確定済み
          </span>
        {/if}
      </div>
    </div>

    <div class="flex shrink-0 items-center gap-2">
      <!-- Connection status -->
      {#if connectionStatus === 'error'}
        <AlertCircle class="h-4 w-4 {statusColor}" aria-label={statusLabel} />
      {:else if connectionStatus === 'disconnected'}
        <WifiOff class="h-4 w-4 {statusColor}" aria-label={statusLabel} />
      {:else}
        <Wifi class="h-4 w-4 {statusColor}" aria-label={statusLabel} />
      {/if}

      <!-- Copy invite link -->
      <button
        onclick={copyLink}
        class="flex items-center gap-1 rounded-lg border border-gray-200 px-2 py-1 text-xs text-gray-600 hover:bg-gray-50"
        aria-label="招待リンクをコピー"
      >
        {#if copied}
          <Check class="h-3.5 w-3.5 text-green-500" />
          コピー済み
        {:else}
          <Share2 class="h-3.5 w-3.5" />
          招待
        {/if}
      </button>
    </div>
  </div>
</div>

// components/split-calculator/settlement-header.tsx
'use client'

import { Check, Copy, Edit2, Lock, Share2 } from 'lucide-react'
import { useState } from 'react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { type ConnectionStatus, SyncStatusIndicator } from './sync-status-indicator'

interface SettlementHeaderProps {
  name: string
  isOwner: boolean
  isLocked: boolean
  inviteLink: string
  connectionStatus: ConnectionStatus
  onNameChange?: (name: string) => void
}

export function SettlementHeader({
  name,
  isOwner,
  isLocked,
  inviteLink,
  connectionStatus,
  onNameChange,
}: SettlementHeaderProps) {
  const [isEditing, setIsEditing] = useState(false)
  const [editName, setEditName] = useState(name)
  const [copied, setCopied] = useState(false)

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(inviteLink)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback for older browsers
      const textArea = document.createElement('textarea')
      textArea.value = inviteLink
      document.body.appendChild(textArea)
      textArea.select()
      document.execCommand('copy')
      document.body.removeChild(textArea)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  const handleSaveName = () => {
    if (editName.trim() && onNameChange) {
      onNameChange(editName.trim())
    }
    setIsEditing(false)
  }

  return (
    <Card className="mb-6 border-2 border-primary/50 bg-primary/5">
      <CardContent className="py-4">
        <div className="flex items-center justify-between gap-4">
          <div className="min-w-0 flex-1">
            {isEditing && isOwner && !isLocked ? (
              <div className="flex items-center gap-2">
                <Input
                  value={editName}
                  onChange={(e) => setEditName(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') handleSaveName()
                    if (e.key === 'Escape') setIsEditing(false)
                  }}
                  className="h-8 text-lg font-bold"
                  autoFocus
                />
                <Button size="sm" onClick={handleSaveName}>
                  保存
                </Button>
              </div>
            ) : (
              <div className="flex items-center gap-2">
                <h2 className="truncate text-xl font-bold text-foreground">{name}</h2>
                {isOwner && !isLocked && (
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-6 w-6 shrink-0"
                    onClick={() => {
                      setEditName(name)
                      setIsEditing(true)
                    }}
                    aria-label="精算名を編集"
                  >
                    <Edit2 className="h-3 w-3" />
                  </Button>
                )}
              </div>
            )}
            <div className="mt-1 flex items-center gap-2">
              <SyncStatusIndicator status={connectionStatus} />
              {isLocked && (
                <Badge variant="secondary" className="gap-1">
                  <Lock className="h-3 w-3" />
                  確定済み
                </Badge>
              )}
              {isOwner && (
                <Badge variant="outline" className="text-xs">
                  オーナー
                </Badge>
              )}
            </div>
          </div>

          <Dialog>
            <DialogTrigger asChild>
              <Button variant="outline" size="sm" className="shrink-0 gap-2 bg-transparent">
                <Share2 className="h-4 w-4" />
                招待
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>メンバーを招待</DialogTitle>
                <DialogDescription>
                  以下のリンクを共有して、他の参加者を招待できます。
                  リンクを知っている人は誰でも参加できます。
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <Input value={inviteLink} readOnly className="font-mono text-xs" />
                  <Button
                    onClick={handleCopyLink}
                    variant="outline"
                    size="icon"
                    className="shrink-0 bg-transparent"
                    aria-label="リンクをコピー"
                  >
                    {copied ? (
                      <Check className="h-4 w-4 text-green-600" />
                    ) : (
                      <Copy className="h-4 w-4" />
                    )}
                  </Button>
                </div>
                {copied && <p className="text-center text-sm text-green-600">コピーしました</p>}
                <p className="text-xs text-muted-foreground">
                  このリンクには招待トークンが含まれています。
                  リンクを共有された人は精算に参加し、支出を追加できます。
                </p>
              </div>
            </DialogContent>
          </Dialog>
        </div>
      </CardContent>
    </Card>
  )
}
